### PR TITLE
Add section for emailCaptureEnabled option in js docs

### PR DESCRIPTION
**Pull request by Mario54**
@lemieux @dannytranlx @alavers @spasiu

### CODE REVIEW

**Comment by lemieux** [comment]
that screenshot is weird

**Comment by lemieux** [comment]
otherwise :+1:

**Comment by Mario54** [comment]
Hmm yeah wtf

**Comment by mspensieri** [comment]
Should note that this feature is not very useful for people using Zendesk, Help Scout or email

**Comment by alavers** [comment]
Yeah we need copy to explain that this is only really useful for channels where you can get a refreshed snapshot of user data.

On that note, I really want us to consider cleaning up and using the f/contact-info-notif thing I did which completely fixes this problem.

**Comment by Mario54** [comment]
Should I leave the copy as if we're doing the contact info notification soon?

If not, is this better?
> As illustrated above, it's possible to prompt your users for their email, after they send their first message. By clicking on "leave us your email", your users will be able to enter their email address which will then be accessible in Slack by using the `/sk !profile` command or in HipChat by opening the profile sidebar.

**Comment by alavers** [comment]
:+1: that copy looks good! No reason not to simply publish it now.

**Pull request merged**
